name: dson_example
version: 0.0.1
author: Luis Vargas <luisvargastijerino@gmail.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  dson:
    path: ../
dev_dependencies:
  build_runner: any
  build_web_compilers: any
dependency_overrides:
#  built_mirrors_core:
#    path: ../../built_mirrors_core
#  serializable_core:
#    path: ../../serializable_core
#  dson_core:
#    path: ../../dson_core
