# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

# analyzer:
#   exclude:
#     - example/**
 linter:
   rules:
      - unnecessary_const
      - unnecessary_new
