builders:
  dson_builder:
    target: :_dson
    import: package:dson/builder.dart
    builder_factories: [builder]
    build_to: source
    auto_apply: root_package
    build_extensions:
      .dart: [.g.dart]