targets:
  $default:
    builders:
      dson:
        generate_for: [example/**, test/**, bench/**]
      serializable:
        generate_for:
          exclude: ['**']
      built_mirrors:
        generate_for:
          exclude: ['**']
builders:
  dson:
    import: package:dson/builder.dart
    builder_factories: [builder]
    auto_apply: dependents
    build_extensions:
      .dart: [.dson.g.part]
    applies_builders: [source_gen|combining_builder]
