name: dson
version: 0.15.5
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  source_gen: ^0.9.0
  build: ^1.0.0
  analyzer: ^0.34.0
  logging: ^0.11.0
  dson_core: ^0.15.4
#  dson_core:
#    path: ../dson_core
  built_mirrors_core: ^0.10.4
  serializable_core: ^0.11.2+1
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
#  built_mirrors_core:
#    path: ../built_mirrors_core
dev_dependencies:
  test: ^1.0.0
  build_test: any
  build_runner: ^1.0.0
