name: dson
version: 0.11.0
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  build_runner: ^0.6.0
  source_gen: ^0.7.0
  build: ^0.11.1
  analyzer: ^0.30.0
  logging: ^0.11.0
  built_mirrors: ^0.7.1
  serializable: ^0.8.0
#  serializable:
#    path: ../serializable
#  built_mirrors:
#    path: ../built_mirrors
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  test: ^0.12.0
transformers:
- test/pub_serve:
    $include: test/**_test.dart
