name: dson
version: 1.0.0
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  source_gen: ^1.2.1
  build: ^2.2.1
  analyzer: ^3.3.1
  logging: ^1.0.2
  built_mirrors: ^1.0.0
#  built_mirrors:
#    path: ../built_mirrors
  serializable: ^1.0.0
#  serializable:
#    path: ../serializable
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
#  serializable:
#    path: ../serializable
dev_dependencies:
  test: ^1.20.2
  build_test: ^2.1.5
  build_runner: ^2.1.8
