name: dson
version: 2.0.0
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  source_gen: ^1.3.2
  build: ^2.4.0
  analyzer: ^5.13.0
  logging: ^1.2.0
  collection: ^1.17.2
  built_mirrors: ^2.0.1
#  built_mirrors:
#    path: ../built_mirrors
  serializable: ^2.0.1
#  serializable:
#    path: ../serializable
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
#  serializable:
#    path: ../serializable
dev_dependencies:
  test: ^1.24.3
  build_test: ^2.1.7
  build_runner: ^2.4.4
