name: dson
version: 0.13.0
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  source_gen: ^0.7.0
  build: ^0.12.0
  analyzer: ^0.31.0
  logging: ^0.11.0
  dson_core: ^0.13.0
#  dson_core:
#    path: ../dson_core
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.7.0
transformers:
- test/pub_serve:
    $include: test/**_test.dart
