name: dson
version: 0.17.0
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  source_gen: ^0.9.0
  build: ^1.0.0
  analyzer: '>=0.36.0 <1.0.0'
  logging: ^0.11.0
  built_mirrors: ^0.12.0
#  built_mirrors:
#    path: ../built_mirrors
  serializable: ^0.13.0
#  serializable:
#    path: ../serializable
dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
#  serializable:
#    path: ../serializable
dev_dependencies:
  test: ^1.0.0
  build_test: ^1.2.0
  build_runner: ^1.0.0
